# Root config ties everything together and sets defaults
defaults:
  - data/dataset: labelled
  - data/loader: imagefolder
  - _self_
  # - model: resnet50
  # - optimizer: adam

# Global defaults
seed: 42
